import { Car } from './types';

// Cloudinary base URL for optimized images
export const CLOUDINARY_BASE_URL = 'https://res.cloudinary.com/devtgyyan/image/upload/f_auto,q_auto/';

// Helper to format currency
export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat('es-ES', {
    style: 'currency',
    currency: 'EUR',
    maximumFractionDigits: 0,
  }).format(price);
};

// Helper to format numbers (km)
export const formatNumber = (num: number): string => {
  return new Intl.NumberFormat('es-ES').format(num);
};

export const MOCK_CARS: Car[] = [
  {
    id: '1',
    make: 'Smart',
    model: 'Fortwo #3',
    year: 2014,
    price: 5500,
    km: 141000,
    fuel: 'Gasolina',
    transmission: 'Automática',
    power: 69,
    color: 'Blanco',
    bodyType: 'Urbano',
    images: [
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/1`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/2`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/3`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/4`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/5`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/6`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/7`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/8`,
    ],
    description: '¡El rey de la ciudad! Smart Fortwo (gen. 451) con fiable motor Mercedes. Estado impecable, ideal para moverte con agilidad y aparcar en cualquier sitio. Incluye 1 año de garantía, ITV hasta 2027 y ¡IVA deducible! Una oportunidad única.'
  },
  {
    id: '2',
    make: 'Renault',
    model: 'Megane',
    year: 2019,
    price: 7500,
    offerPrice: 6500,

    km: 225000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 132,
    color: 'Blanco',
    bodyType: 'Compacto',
    images: [
      `${CLOUDINARY_BASE_URL}images/renault-megane/1`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/2`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/3`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/4`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/5`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/6`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/7`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/8`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/9`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/10`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/11`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/12`,
    ],
    description: 'Vehículo de un único propietario, con un mantenimiento exhaustivo que incluye la revisión de la cadena de distribución. Se encuentra en un estado excelente, prácticamente como nuevo. Ideal para quien busca fiabilidad y un coche bien cuidado a un precio competitivo.'
  },
  {
    id: '3',
    make: 'Seat',
    model: 'Altea',
    year: 2012,
    price: 5850,
    km: 165000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 125,
    color: 'Gris Plata',
    bodyType: 'Monovolumen',
    images: [
      `${CLOUDINARY_BASE_URL}images/seat-altea/1`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/2`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/3`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/4`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/5`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/6`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/7`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/8`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/9`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/10`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/11`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/12`,
    ],
    description: 'Monovolumen seminuevo en excelente estado. Se entrega con una garantía completa de 1 año y una revisión exhaustiva recién realizada. Equipado con un fiable motor con cadena de distribución. Un vehículo espacioso y versátil, ideal para familias. ¡Un auténtico cochazo!',
    isSold: true
  },
  {
    id: '4',
    make: 'Mercedes-Benz',
    model: 'Clase CLA',
    year: 2009,
    price: 14900,
    km: 145000,
    fuel: 'Gasolina',
    transmission: 'Automática',
    power: 156,
    color: 'Blanco',
    bodyType: 'Sedán',
    images: [
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/1`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/2`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/3`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/4`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/5`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/6`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/7`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/8`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/9`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/10`,
    ],
    description: 'Impecable Mercedes-Benz Clase CLA de un único propietario, cuidado con esmero y guardado siempre en garaje. Combina elegancia y deportividad con su cambio automático. Se entrega con 1 año de garantía para tu total tranquilidad.'
  },
  {
    id: '5',
    make: 'Smart',
    model: 'Fortwo #1',
    year: 2009,
    price: 3750,
    km: 132000,
    fuel: 'Gasolina',
    transmission: 'Automática',
    power: 69,
    color: 'Negro',
    bodyType: 'Urbano',
    images: [
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/1`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/2`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/3`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/4`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/5`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/6`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/7`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/8`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/9`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/10`,
    ],
    description: 'Smart con el fiable motor Mercedes, en un estado de conservación excelente. Perfecto para la ciudad por su agilidad y facilidad de aparcamiento. Se entrega con 1 año de garantía y la revisión recién hecha.'
  },
  {
    id: '6',
    make: 'Mini',
    model: 'Cooper One',
    year: 2007,
    price: 5500,
    offerPrice: 4500,
    km: 201000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 116,
    color: 'Rojo',
    bodyType: 'Compacto',
    images: [
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/1`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/2`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/3`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/4`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/5`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/6`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/7`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/8`,
    ],
    description: 'Mini Cooper One con el fiable motor BMW de 1.6L y 116 CV. Equipado con techo solar y asientos de piel. Un icono de estilo y agilidad en un estado de conservación excelente. ¡Aprovecha esta oferta especial!'
  },
  {
    id: '7',
    make: 'BMW',
    model: 'GS 1200',
    year: 2013,
    price: 12500,
    km: 92000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 125,
    color: 'Blanco y Negro',
    bodyType: 'Moto',
    images: [
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/1`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/2`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/3`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/4`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/5`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/6`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/7`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/8`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/9`,
    ],
    description: 'Edición limitada de la icónica BMW GS 1200. Equipada hasta el último detalle: escape Akrapovic, juego de maletas completo, pantalla alta y luces de ruta. Proviene de un único dueño y su estado es mejor que nueva. Una oportunidad única para los amantes de la aventura.'
  },
  {
    id: '9',
    make: 'Mercedes-Benz',
    model: 'Clase E',
    year: 2007,
    price: 7950,
    km: 140000,
    fuel: 'Gasolina',
    transmission: 'Automática',
    power: 265,
    color: 'Gris',
    bodyType: 'Sedán',
    images: [
      `${CLOUDINARY_BASE_URL}images/mercedes-e/1`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/2`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/3`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/4`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/5`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/6`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/7`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/8`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/9`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/10`,
    ],
    description: 'Elegante Mercedes-Benz Clase E del 2007 con un potente motor de 265 CV. Proviene de un único propietario y ha sido guardado siempre en garaje, presentando un estado de conservación excepcional, como nuevo. Una berlina de lujo, fiable y potente, ideal para quien busca confort y prestaciones.'
  },
  {
    id: '10',
    make: 'Renault',
    model: 'Megane Sport Tourer ST 1.3',
    year: 2019,
    price: 9800,
    km: 136000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 140,
    color: 'Gris',
    bodyType: 'Familiar',
    images: [
      `${CLOUDINARY_BASE_URL}images/renault-megane-sport/1`,
      `${CLOUDINARY_BASE_URL}images/renault-megane-sport/2`,
      `${CLOUDINARY_BASE_URL}images/renault-megane-sport/3`,
      `${CLOUDINARY_BASE_URL}images/renault-megane-sport/4`,
      `${CLOUDINARY_BASE_URL}images/renault-megane-sport/5`,
      `${CLOUDINARY_BASE_URL}images/renault-megane-sport/6`,
      `${CLOUDINARY_BASE_URL}images/renault-megane-sport/7`,
      `${CLOUDINARY_BASE_URL}images/renault-megane-sport/8`,
    ],
    description: 'Renault Megane Sport Tourer ST con motor 1.3 de 140 CV y etiqueta C. Un vehículo familiar versátil y potente, con 136.000 km. Se entrega con 1 año de garantía, recién revisado y con la ITV en vigor hasta 2027. Ideal para quienes buscan espacio y eficiencia.'
  },
  {
    id: '11',
    make: 'Citroen',
    model: 'Cactus C4 Pure',
    year: 2016,
    price: 6500,
    km: 112000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 82,
    color: 'Blanco',
    bodyType: 'Compacto',
    images: [
      `${CLOUDINARY_BASE_URL}images/citroen-cactus-c4/1`,
      `${CLOUDINARY_BASE_URL}images/citroen-cactus-c4/2`,
      `${CLOUDINARY_BASE_URL}images/citroen-cactus-c4/3`,
      `${CLOUDINARY_BASE_URL}images/citroen-cactus-c4/4`,
      `${CLOUDINARY_BASE_URL}images/citroen-cactus-c4/5`,
      `${CLOUDINARY_BASE_URL}images/citroen-cactus-c4/6`,
      `${CLOUDINARY_BASE_URL}images/citroen-cactus-c4/7`,
      `${CLOUDINARY_BASE_URL}images/citroen-cactus-c4/8`,
      `${CLOUDINARY_BASE_URL}images/citroen-cactus-c4/9`,
    ],
    description: 'Citroen Cactus C4 Pure de 82 CV gasolina con etiqueta C. Vehículo en excelente estado, con 112.000 km. Recién revisado y con 1 año de garantía incluido. Una opción económica, fiable y con un diseño único.'
  },
  {
    id: '12',
    make: 'Peugeot',
    model: '207',
    year: 2010,
    price: 3500,
    km: 114000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 120,
    color: 'Gris',
    bodyType: 'Compacto',
    images: [
      `${CLOUDINARY_BASE_URL}images/peageut-207/1`,
      `${CLOUDINARY_BASE_URL}images/peageut-207/2`,
      `${CLOUDINARY_BASE_URL}images/peageut-207/3`,
      `${CLOUDINARY_BASE_URL}images/peageut-207/4`,
      `${CLOUDINARY_BASE_URL}images/peageut-207/5`,
      `${CLOUDINARY_BASE_URL}images/peageut-207/6`,
      `${CLOUDINARY_BASE_URL}images/peageut-207/7`,
      `${CLOUDINARY_BASE_URL}images/peageut-207/8`,
    ],
    description: 'Peugeot 207 con motor 1.6 de 16 válvulas y 120 CV. Etiqueta C de gasolina. Procedente de un solo dueño, con tan solo 114.000 km. Año 2010. Un coche fiable, bien cuidado y con un consumo equilibrado.'
  },
  {
    id: '13',
    make: 'Nissan',
    model: 'Quasqai 1.3',
    year: 2022,
    price: 17500,
    km: 145000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 140,
    color: 'Gris',
    bodyType: 'SUV',
    images: [
      `${CLOUDINARY_BASE_URL}images/nissan-quasqai/1`,
      `${CLOUDINARY_BASE_URL}images/nissan-quasqai/2`,
      `${CLOUDINARY_BASE_URL}images/nissan-quasqai/3`,
      `${CLOUDINARY_BASE_URL}images/nissan-quasqai/4`,
      `${CLOUDINARY_BASE_URL}images/nissan-quasqai/5`,
      `${CLOUDINARY_BASE_URL}images/nissan-quasqai/6`,
      `${CLOUDINARY_BASE_URL}images/nissan-quasqai/7`,
      `${CLOUDINARY_BASE_URL}images/nissan-quasqai/8`,
    ],
    description: 'Nissan Quasqai 1.3 de 140 CV gasolina con etiqueta C. Vehículo del año 2022 con 145.000 km. Se entrega con 1 año de garantía incluido. Un SUV moderno, espacioso y muy fiable.'
  },
  {
    id: '14',
    make: 'Volkswagen',
    model: 'Polo GTI',
    year: 2010,
    price: 13900,
    km: 150000,
    fuel: 'Gasolina',
    transmission: 'Automática',
    power: 310,
    color: 'Blanco',
    bodyType: 'Compacto',
    images: [
      `${CLOUDINARY_BASE_URL}images/polo-gti/1`,
      `${CLOUDINARY_BASE_URL}images/polo-gti/2`,
      `${CLOUDINARY_BASE_URL}images/polo-gti/3`,
      `${CLOUDINARY_BASE_URL}images/polo-gti/4`,
      `${CLOUDINARY_BASE_URL}images/polo-gti/5`,
      `${CLOUDINARY_BASE_URL}images/polo-gti/6`,
      `${CLOUDINARY_BASE_URL}images/polo-gti/7`,
      `${CLOUDINARY_BASE_URL}images/polo-gti/8`,
      `${CLOUDINARY_BASE_URL}images/polo-gti/9`,
      `${CLOUDINARY_BASE_URL}images/polo-gti/10`,
    ],
    description: 'Volkswagen Polo GTI único en España. Motor reprogramado por mecánico profesional alcanzando los 310 CV. Full equip: asientos de piel, techo solar, cambio automático DSG con levas en el volante y llantas deportivas. Un coche exclusivo con 150.000 km y 1 año de garantía.',
    isUnique: true
  },
  {
    id: '15',
    make: 'Volkswagen',
    model: 'Golf R',
    year: 2015,
    price: 25900,
    km: 135000,
    fuel: 'Gasolina',
    transmission: 'Automática',
    power: 408,
    color: 'Azul',
    bodyType: 'Compacto',
    images: [
      `${CLOUDINARY_BASE_URL}images/golf-r/1`,
      `${CLOUDINARY_BASE_URL}images/golf-r/2`,
      `${CLOUDINARY_BASE_URL}images/golf-r/3`,
      `${CLOUDINARY_BASE_URL}images/golf-r/4`,
      `${CLOUDINARY_BASE_URL}images/golf-r/5`,
      `${CLOUDINARY_BASE_URL}images/golf-r/6`,
    ],
    description: 'Espectacular Volkswagen Golf R con 408 CV. Cuenta con 2 reprogramaciones realizadas por expertos para un rendimiento óptimo. Totalmente equipado: techo solar, asientos de piel, cambio automático DSG con levas. Un vehículo de altas prestaciones con 135.000 km y 1 año de garantía.'
  },
  {
    id: '16',
    make: 'Jeep',
    model: 'Patriot',
    year: 2011,
    price: 9800,
    km: 200000,
    fuel: 'Diesel',
    transmission: 'Manual',
    power: 160,
    color: 'A consultar',
    bodyType: 'SUV',
    images: [
      `${CLOUDINARY_BASE_URL}images/jeep-patriot/1`,
      `${CLOUDINARY_BASE_URL}images/jeep-patriot/2`,
      `${CLOUDINARY_BASE_URL}images/jeep-patriot/3`,
      `${CLOUDINARY_BASE_URL}images/jeep-patriot/4`,
      `${CLOUDINARY_BASE_URL}images/jeep-patriot/5`,
      `${CLOUDINARY_BASE_URL}images/jeep-patriot/6`,
      `${CLOUDINARY_BASE_URL}images/jeep-patriot/7`,
      `${CLOUDINARY_BASE_URL}images/jeep-patriot/8`,
    ],
    description: 'Jeep Patriot con motor nuevo. Revisión reciente y 1 año de garantía. Un SUV robusto y fiable con 160 CV.'
  },
  {
    id: '17',
    make: 'Volkswagen',
    model: 'Touran',
    year: 2010,
    price: 8500,
    km: 150000,
    fuel: 'Diesel',
    transmission: 'Automática',
    power: 110,
    color: 'A consultar',
    bodyType: 'Monovolumen',
    images: [
      `${CLOUDINARY_BASE_URL}images/volkswagen-touran/1`,
      `${CLOUDINARY_BASE_URL}images/volkswagen-touran/2`,
      `${CLOUDINARY_BASE_URL}images/volkswagen-touran/3`,
      `${CLOUDINARY_BASE_URL}images/volkswagen-touran/4`,
      `${CLOUDINARY_BASE_URL}images/volkswagen-touran/5`,
      `${CLOUDINARY_BASE_URL}images/volkswagen-touran/6`,
      `${CLOUDINARY_BASE_URL}images/volkswagen-touran/7`,
      `${CLOUDINARY_BASE_URL}images/volkswagen-touran/8`,
      `${CLOUDINARY_BASE_URL}images/volkswagen-touran/9`,
      `${CLOUDINARY_BASE_URL}images/volkswagen-touran/10`,
    ],
    description: 'Volkswagen Touran en estado impecable. Equipada con cambio automático DSG, techo solar y llantas de aleación. Un monovolumen fiable y espacioso con 150.000 km.'
  },
  {
    id: '18',
    make: 'Peugeot',
    model: '207 Familiar',
    year: 2011,
    price: 3000,
    km: 155000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 90,
    color: 'A consultar',
    bodyType: 'Familiar',
    images: [
      `${CLOUDINARY_BASE_URL}images/peageut-207-familiar/1`,
      `${CLOUDINARY_BASE_URL}images/peageut-207-familiar/2`,
      `${CLOUDINARY_BASE_URL}images/peageut-207-familiar/3`,
      `${CLOUDINARY_BASE_URL}images/peageut-207-familiar/4`,
      `${CLOUDINARY_BASE_URL}images/peageut-207-familiar/5`,
      `${CLOUDINARY_BASE_URL}images/peageut-207-familiar/6`,
      `${CLOUDINARY_BASE_URL}images/peageut-207-familiar/7`,
      `${CLOUDINARY_BASE_URL}images/peageut-207-familiar/8`,
    ],
    description: 'Peugeot 207 familiar del año 2011 con 155.000 km y 90 CV. Etiqueta C. Se entrega con revisión recién hecha y 1 año de garantía. Un vehículo versátil y fiable.'
  },
  {
    id: '19',
    make: 'Land Rover',
    model: 'Sport',
    year: 2011,
    price: 9500,
    km: 266000,
    fuel: 'Diesel',
    transmission: 'Automática',
    power: 190,
    color: 'A consultar',
    bodyType: 'SUV',
    images: [
      `${CLOUDINARY_BASE_URL}images/land-rover-sport/1`,
      `${CLOUDINARY_BASE_URL}images/land-rover-sport/2`,
      `${CLOUDINARY_BASE_URL}images/land-rover-sport/3`,
      `${CLOUDINARY_BASE_URL}images/land-rover-sport/4`,
      `${CLOUDINARY_BASE_URL}images/land-rover-sport/5`,
      `${CLOUDINARY_BASE_URL}images/land-rover-sport/6`,
      `${CLOUDINARY_BASE_URL}images/land-rover-sport/7`,
      `${CLOUDINARY_BASE_URL}images/land-rover-sport/8`,
    ],
    description: 'Land Rover Sport del año 2011 con 190 CV. Equipado con asientos de piel y techo solar. Cambio automático para un confort máximo. Se entrega con 1 año de garantía.'
  },
  {
    id: '20',
    make: 'Peugeot',
    model: '308',
    year: 2015,
    price: 5000,
    km: 147000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 130,
    color: 'A consultar',
    bodyType: 'Compacto',
    images: [
      `${CLOUDINARY_BASE_URL}images/peageut-308/1`,
      `${CLOUDINARY_BASE_URL}images/peageut-308/2`,
      `${CLOUDINARY_BASE_URL}images/peageut-308/3`,
      `${CLOUDINARY_BASE_URL}images/peageut-308/4`,
      `${CLOUDINARY_BASE_URL}images/peageut-308/5`,
      `${CLOUDINARY_BASE_URL}images/peageut-308/6`,
      `${CLOUDINARY_BASE_URL}images/peageut-308/7`,
      `${CLOUDINARY_BASE_URL}images/peageut-308/8`,
    ],
    description: 'Peugeot 308 del año 2015 con 147.000 km y 130 CV. Etiqueta C. Se entrega con revisión recién hecha y 1 año de garantía. Un coche fiable y bien cuidado.'
  },
  {
    id: '21',
    make: 'Mini',
    model: 'Cooper R50',
    year: 2007,
    price: 3900,
    km: 200000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 116,
    color: 'A consultar',
    bodyType: 'Compacto',
    images: [
      `${CLOUDINARY_BASE_URL}images/mini-cooper-r50/1`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-r50/2`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-r50/3`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-r50/4`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-r50/5`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-r50/6`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-r50/7`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-r50/8`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-r50/9`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-r50/10`,
    ],
    description: 'Mini Cooper R50 con el fiable motor BMW de 116 CV. En estado perfecto, equipado con asientos de piel y techo solar. Se entrega con 1 año de garantía.'
  },
  {
    id: '22',
    make: 'Dacia',
    model: 'Lodgy 7pl TCe Laureate',
    year: 2017,
    price: 11200,
    km: 78000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 115,
    color: 'Blanco',
    bodyType: 'Monovolumen',
    images: [
      `${CLOUDINARY_BASE_URL}images/dacia-lodgy/1`,
      `${CLOUDINARY_BASE_URL}images/dacia-lodgy/2`,
      `${CLOUDINARY_BASE_URL}images/dacia-lodgy/3`,
      `${CLOUDINARY_BASE_URL}images/dacia-lodgy/4`,
      `${CLOUDINARY_BASE_URL}images/dacia-lodgy/5`,
      `${CLOUDINARY_BASE_URL}images/dacia-lodgy/6`,
      `${CLOUDINARY_BASE_URL}images/dacia-lodgy/7`,
      `${CLOUDINARY_BASE_URL}images/dacia-lodgy/8`,
    ],
    description: 'Excelente Dacia Lodgy de 7 plazas en Gavà (Barcelona), versión 1.6 TCe 115 Laureate (tope de gama). Un único propietario, con 78.000 km y etiqueta C. Precio al contado: 11.200 € | Precio financiado: 11.000 €. Financiación sin entrada desde 150 €/mes. Equipado con aire acondicionado, control de crucero, volante multifunción, faros antiniebla, alarma volumétrica e Isofix. Se entrega con revisión recién hecha, garantía y cambio de nombre incluido.'
  },
  {
    id: '23',
    make: 'Citroën',
    model: 'Jumper L1H1 2.2 BlueHDi 140',
    year: 2021,
    price: 15900,
    km: 131000,
    fuel: 'Diesel',
    transmission: 'Manual',
    power: 140,
    color: 'Blanco',
    bodyType: 'Furgoneta',
    images: [
      `${CLOUDINARY_BASE_URL}images/citroen-jumper/1`,
      `${CLOUDINARY_BASE_URL}images/citroen-jumper/2`,
      `${CLOUDINARY_BASE_URL}images/citroen-jumper/3`,
      `${CLOUDINARY_BASE_URL}images/citroen-jumper/4`,
      `${CLOUDINARY_BASE_URL}images/citroen-jumper/5`,
      `${CLOUDINARY_BASE_URL}images/citroen-jumper/6`,
      `${CLOUDINARY_BASE_URL}images/citroen-jumper/7`,
      `${CLOUDINARY_BASE_URL}images/citroen-jumper/8`,
      `${CLOUDINARY_BASE_URL}images/citroen-jumper/9`,
    ],
    description: 'Citroën Jumper 2021 L1H1 2.2 BlueHDi 140 CV en Gavà (Barcelona). Furgoneta de 3 plazas con 131.000 km y etiqueta C (Verde). Precio al contado: 15.900 € (IVA incluido) | Precio financiado: 15.700 €. Financiación al 100% sin entrada. Muy cuidada, con revisión recién hecha. Equipada con cámara de marcha atrás, bola de remolque, barras de techo, control de crucero, volante multifunción y Bluetooth. Ideal para uso profesional o comercial.'
  },
  {
    id: '24',
    make: 'BMW',
    model: 'Serie 7',
    year: 2010,
    price: 15900,
    km: 131000,
    fuel: 'Gasolina',
    transmission: 'Automática',
    power: 408,
    color: 'Negro',
    bodyType: 'Sedán',
    images: [
      `${CLOUDINARY_BASE_URL}images/bmw-serie7/1`,
      `${CLOUDINARY_BASE_URL}images/bmw-serie7/2`,
      `${CLOUDINARY_BASE_URL}images/bmw-serie7/3`,
      `${CLOUDINARY_BASE_URL}images/bmw-serie7/4`,
      `${CLOUDINARY_BASE_URL}images/bmw-serie7/5`,
      `${CLOUDINARY_BASE_URL}images/bmw-serie7/6`,
      `${CLOUDINARY_BASE_URL}images/bmw-serie7/7`,
      `${CLOUDINARY_BASE_URL}images/bmw-serie7/8`,
    ],
    description: 'Impresionante BMW Serie 7 con un potente motor de 408 CV y etiqueta C. Se entrega con revisión recién hecha e ITV al día para su total tranquilidad. Un lujo de berlina con 131.000 km y 1 año de garantía incluido. Un vehículo imponente y confortable.'
  }
];

export const COMPANY_PHONE = "+34647606425";
export const COMPANY_WHATSAPP = "34647606425";