import { Car } from './types';

// Cloudinary base URL for optimized images
export const CLOUDINARY_BASE_URL = 'https://res.cloudinary.com/devtgyyan/image/upload/f_auto,q_auto/';

// Helper to format currency
export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat('es-ES', {
    style: 'currency',
    currency: 'EUR',
    maximumFractionDigits: 0,
  }).format(price);
};

// Helper to format numbers (km)
export const formatNumber = (num: number): string => {
  return new Intl.NumberFormat('es-ES').format(num);
};

export const MOCK_CARS: Car[] = [
  {
    id: '1',
    make: 'Smart',
    model: 'Fortwo #3',
    year: 2014,
    price: 5500,
    km: 141000,
    fuel: 'Gasolina',
    transmission: 'Automática',
    power: 69,
    color: 'Blanco',
    bodyType: 'Urbano',
    images: [
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/1`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/2`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/3`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/4`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/5`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/6`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/7`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo/8`,
    ],
    description: '¡El rey de la ciudad! Smart Fortwo (gen. 451) con fiable motor Mercedes. Estado impecable, ideal para moverte con agilidad y aparcar en cualquier sitio. Incluye 1 año de garantía, ITV hasta 2027 y ¡IVA deducible! Una oportunidad única.'
  },
  {
    id: '2',
    make: 'Renault',
    model: 'Megane',
    year: 2019,
    price: 7500,
    km: 225000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 132,
    color: 'Blanco',
    bodyType: 'Compacto',
    images: [
      `${CLOUDINARY_BASE_URL}images/renault-megane/1`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/2`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/3`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/4`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/5`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/6`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/7`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/8`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/9`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/10`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/11`,
      `${CLOUDINARY_BASE_URL}images/renault-megane/12`,
    ],
    description: 'Vehículo de un único propietario, con un mantenimiento exhaustivo que incluye la revisión de la cadena de distribución. Se encuentra en un estado excelente, prácticamente como nuevo. Ideal para quien busca fiabilidad y un coche bien cuidado a un precio competitivo.'
  },
  {
    id: '3',
    make: 'Seat',
    model: 'Altea',
    year: 2012,
    price: 5850,
    km: 165000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 125,
    color: 'Gris Plata',
    bodyType: 'Monovolumen',
    images: [
      `${CLOUDINARY_BASE_URL}images/seat-altea/1`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/2`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/3`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/4`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/5`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/6`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/7`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/8`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/9`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/10`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/11`,
      `${CLOUDINARY_BASE_URL}images/seat-altea/12`,
    ],
    description: 'Monovolumen seminuevo en excelente estado. Se entrega con una garantía completa de 1 año y una revisión exhaustiva recién realizada. Equipado con un fiable motor con cadena de distribución. Un vehículo espacioso y versátil, ideal para familias. ¡Un auténtico cochazo!'
  },
  {
    id: '4',
    make: 'Mercedes-Benz',
    model: 'Clase CLA',
    year: 2009,
    price: 14900,
    km: 145000,
    fuel: 'Gasolina',
    transmission: 'Automática',
    power: 156,
    color: 'Blanco',
    bodyType: 'Sedán',
    images: [
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/1`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/2`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/3`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/4`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/5`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/6`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/7`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/8`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/9`,
      `${CLOUDINARY_BASE_URL}images/mercedes-cla/10`,
    ],
    description: 'Impecable Mercedes-Benz Clase CLA de un único propietario, cuidado con esmero y guardado siempre en garaje. Combina elegancia y deportividad con su cambio automático. Se entrega con 1 año de garantía para tu total tranquilidad.'
  },
  {
    id: '5',
    make: 'Smart',
    model: 'Fortwo #1',
    year: 2009,
    price: 3750,
    km: 132000,
    fuel: 'Gasolina',
    transmission: 'Automática',
    power: 69,
    color: 'Negro',
    bodyType: 'Urbano',
    images: [
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/1`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/2`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/3`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/4`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/5`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/6`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/7`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/8`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/9`,
      `${CLOUDINARY_BASE_URL}images/smart-fortwo-1/10`,
    ],
    description: 'Smart con el fiable motor Mercedes, en un estado de conservación excelente. Perfecto para la ciudad por su agilidad y facilidad de aparcamiento. Se entrega con 1 año de garantía y la revisión recién hecha.'
  },
  {
    id: '6',
    make: 'Mini',
    model: 'Cooper One',
    year: 2007,
    price: 5500,
    offerPrice: 4500,
    km: 201000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 116,
    color: 'Rojo',
    bodyType: 'Compacto',
    images: [
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/1`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/2`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/3`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/4`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/5`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/6`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/7`,
      `${CLOUDINARY_BASE_URL}images/mini-cooper-one/8`,
    ],
    description: 'Mini Cooper One con el fiable motor BMW de 1.6L y 116 CV. Equipado con techo solar y asientos de piel. Un icono de estilo y agilidad en un estado de conservación excelente. ¡Aprovecha esta oferta especial!'
  },
  {
    id: '7',
    make: 'BMW',
    model: 'GS 1200',
    year: 2013,
    price: 2500,
    km: 92000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 125,
    color: 'Blanco y Negro',
    bodyType: 'Moto',
    images: [
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/1`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/2`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/3`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/4`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/5`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/6`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/7`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/8`,
      `${CLOUDINARY_BASE_URL}images/bmw-gs-1200/9`,
    ],
    description: 'Edición limitada de la icónica BMW GS 1200. Equipada hasta el último detalle: escape Akrapovic, juego de maletas completo, pantalla alta y luces de ruta. Proviene de un único dueño y su estado es mejor que nueva. Una oportunidad única para los amantes de la aventura.'
  },
  {
    id: '8',
    make: 'Citroen',
    model: 'C4 Cactus',
    year: 2016,
    price: 8500,
    offerPrice: 7000,
    km: 118000,
    fuel: 'Gasolina',
    transmission: 'Manual',
    power: 82,
    color: 'Rojo',
    bodyType: 'Compacto',
    images: [
      `${CLOUDINARY_BASE_URL}images/citroen-c4-cactus/1`,
      `${CLOUDINARY_BASE_URL}images/citroen-c4-cactus/2`,
      `${CLOUDINARY_BASE_URL}images/citroen-c4-cactus/3`,
      `${CLOUDINARY_BASE_URL}images/citroen-c4-cactus/4`,
      `${CLOUDINARY_BASE_URL}images/citroen-c4-cactus/5`,
      `${CLOUDINARY_BASE_URL}images/citroen-c4-cactus/6`,
      `${CLOUDINARY_BASE_URL}images/citroen-c4-cactus/7`,
      `${CLOUDINARY_BASE_URL}images/citroen-c4-cactus/8`,
    ],
    description: 'Atrevido y eficiente Citroen C4 Cactus 1.2 PureTech. Se entrega con revisión completa, correa de distribución nueva e ITV recién pasada. Incluye 1 año de garantía para tu total tranquilidad. ¡Una oportunidad excelente con un precio de oferta!'
  },
  {
    id: '9',
    make: 'Mercedes-Benz',
    model: 'Clase E',
    year: 2007,
    price: 7950,
    km: 140000,
    fuel: 'Gasolina',
    transmission: 'Automática',
    power: 265,
    color: 'Gris',
    bodyType: 'Sedán',
    images: [
      `${CLOUDINARY_BASE_URL}images/mercedes-e/1`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/2`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/3`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/4`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/5`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/6`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/7`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/8`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/9`,
      `${CLOUDINARY_BASE_URL}images/mercedes-e/10`,
    ],
    description: 'Elegante Mercedes-Benz Clase E del 2007 con un potente motor de 265 CV. Proviene de un único propietario y ha sido guardado siempre en garaje, presentando un estado de conservación excepcional, como nuevo. Una berlina de lujo, fiable y potente, ideal para quien busca confort y prestaciones.'
  }
];

export const COMPANY_PHONE = "+34647606425";
export const COMPANY_WHATSAPP = "34647606425";